### PR TITLE
Suggesting: GH style Markdown+Jekyll publishing?

### PR DESCRIPTION
**Pull request by eonj**
First of all, congratulations you all came to GitHub with open-gpu-doc from NVIDIA.

What I've found first in this repository was separate `README.md` and `index.html` on root, and even with `_config.yml`. Normally GH Pages serves `index.html` if it exists, but with `_config.yml`, Jekyll builds `README.md` or `index.md` into `index.html`.

I think at first `README.md` was being served built with Jekyll, but manually created `index.html` became overriding that. So how about making index pages (and moreover the documents themselves) with Markdown, building with Jekyll? So they becomes both browsible in GH Project site and in GH Pages site.

This PR is from my fork. `README.md` and `index.html` is merged into `index.md`. Some of the text is dropped because it can be displayed in GH Project description. You can see the project description example on <https://github.com/eonj/open-gpu-doc> and the Jekyll build result in <https://eonj.github.io/open-gpu-doc/>.

Hope you like this suggestion.

### CODE REVIEW

**Comment by 1ace** [comment]
Can I make one suggestion? Keeping the index named `README.md` means GitHub will display it on the main repo page, which I think helps a lot.

I think all this takes is to add this to the `_config.yml`:
```
plugins:
  - jekyll-readme-index
```

(Haven't tested this though, ignore me if that doesn't work)

**Comment by annoying258** [comment]
Forked https://github.com/eonj/open-gpu-doc + add https://github.com/NVIDIA/open-gpu-doc/pull/1#issuecomment-519553414

The readme can either be downloaded or viewed using a document viewer (assuming there is one on the OS).

**Comment by blogdron** [comment]
**offtopic**

Convert **HTML** to **Markdown** .  For automatic convert maybe use pandoc

**Comment by praveen8ae** [comment]
why is this PR still open?
and do you guys accept new PR's?

**Pull request closed without merging**
